name: Run code every hour

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures à xx:00
  workflow_dispatch:      # permet aussi de le lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Assure-toi d'avoir la version de Python souhaitée

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tu as un fichier requirements.txt

      - name: Run my script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python oddsapi.py
